# -*- coding: utf-8 -*-
"""QuickCommerce_Picker_Tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wVDWIDWPww8QT43mCjNlDIUCCHCj_znP
"""

import csv

# Bonus calculator function
def calculate_bonus(orders):
    if orders > 50:
        return 500
    elif orders > 30:
        return 200
    else:
        return 0

# Ask how many pickers
num = int(input("How many pickers today? "))
pickers = []

# Collect data
for i in range(num):
    print(f"\n--- Picker {i+1} ---")
    name = input("Name: ")
    orders = int(input("Orders Packed: "))
    hours = float(input("Hours Worked: "))
    break_time = float(input("Break Time: "))

    eff_hours = hours - break_time
    efficiency = orders / eff_hours if eff_hours > 0 else 0
    bonus = calculate_bonus(orders)

    picker_report = {
        "name": name,
        "orders": orders,
        "efficiency": round(efficiency, 2),
        "bonus": bonus
    }

    pickers.append(picker_report)

# Save to CSV
filename = "picker_report.csv"
with open(filename, mode='w', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=["name", "orders", "efficiency", "bonus"])
    writer.writeheader()
    writer.writerows(pickers)

print(f"\n📁 Picker report saved to {filename} ✅")

# Print summary
print("\n===== Daily Summary =====")
for p in pickers:
    print(f"{p['name']} - {p['orders']} orders - {p['efficiency']} orders/hr - ₹{p['bonus']} bonus")