# -*- coding: utf-8 -*-
"""QuickCommerce_Picker_Tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wVDWIDWPww8QT43mCjNlDIUCCHCj_znP
"""

# Step 1: Input Picker Performance Data

print("📦 QuickCommerce Picker Daily Report")

name = input("Enter picker name: ")
orders = int(input("Enter total orders packed today: "))
hours_worked = float(input("Enter total hours worked: "))
break_time = float(input("Enter total break time (in hours): "))

# Step 2: Effective Work Hours
effective_hours = hours_worked - break_time
efficiency = orders / effective_hours if effective_hours > 0 else 0

# Step 3: Bonus Logic
if orders > 50:
    bonus = 500
elif orders > 30:
    bonus = 200
else:
    bonus = 0

# Step 4: Output Report
print("\n--- Picker Performance Report ---")
print("Name:", name)
print("Orders Packed:", orders)
print("Effective Hours:", round(effective_hours, 2))
print("Efficiency:", round(efficiency, 2), "orders/hour")
print("Bonus Earned: ₹", bonus)